Vagrant.configure("2") do |config|
  config.vm.hostname = "db01"
  config.vm.box = "centos/7"

  config.vm.network "forwarded_port", guest: 3306, host: 3306 #, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.1.4"
  config.vm.provision "shell", path: "provision.sh"
end